// Minimal TOML emitter for the website content files under catalog/website/.
// Handles exactly the constrained shape those files use: top-level string
// fields, [skills.<name>] tables of strings, and [[…highlights]] /
// [[…workflow]] arrays of string-field tables.

function tomlString(value) {
  const s = String(value ?? "");
  return `"${s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")}"`;
}

function emitFields(obj, keys) {
  return keys
    .filter((key) => obj[key] != null && obj[key] !== "")
    .map((key) => `${key} = ${tomlString(obj[key])}`);
}

const GENERATED_HEADER =
  "# Maintained in catalog/website/ (generated by scripts/update-plugin-website.mjs on first resolve; edit freely — this file wins over any plugin-repo copy).";

export function emitPluginToml(plugin) {
  return [
    GENERATED_HEADER,
    "",
    ...emitFields(plugin, [
      "display_name",
      "tagline",
      "repo",
      "source_hash",
      "content_hash",
    ]),
    "",
  ].join("\n");
}

export function emitSkillsToml(skills) {
  const lines = [GENERATED_HEADER];
  for (const [name, entry] of Object.entries(skills)) {
    lines.push("", `[skills.${name}]`);
    lines.push(
      ...emitFields(entry, [
        "display_name",
        "tagline",
        "short_summary",
        "full_summary",
        "source_hash",
        "content_hash",
      ]),
    );
    for (const highlight of entry.highlights ?? []) {
      lines.push("", `[[skills.${name}.highlights]]`);
      lines.push(...emitFields(highlight, ["title", "description"]));
    }
    for (const step of entry.workflow ?? []) {
      lines.push("", `[[skills.${name}.workflow]]`);
      lines.push(...emitFields(step, ["name", "description", "details"]));
    }
  }
  lines.push("");
  return lines.join("\n");
}
