// GENERATED by build.mjs from plugins/zelda-sounds/bindings/opencode.json — DO NOT EDIT.
// Edit the canonical source under plugins/zelda-sounds/ and re-run `node build.mjs`.
//
// OpenCode plugin: plays Zelda sound cues on lifecycle events. Each bound event
// spawns the bundled player (../hooks/play-configured-sound.mjs) with a tool-
// neutral moment id; the player resolves the user's configured sound (shared at
// ~/.config/zelda-sounds.json) or the packaged default and plays it.

import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { homedir } from "node:os";
import type { Plugin } from "@opencode-ai/plugin";

// Resolve assets relative to this plugin file (<dist>/plugin/zelda-sounds.ts), so
// the distribution root is its parent's parent. We must NOT shell out to a JS
// runtime to run the .mjs player: OpenCode runs on a compiled Bun binary, so
// process.execPath is the opencode executable (not node) and would fail. Instead
// the plugin resolves the moment's sound itself and spawns the OS-native shell
// player (hooks/play-sound.sh) directly -- no node/bun dependency.
const DIST = dirname(dirname(fileURLToPath(import.meta.url)));
const SOUNDS_DIR = join(DIST, "sounds");
const DEFAULTS_JSON = join(DIST, "config", "defaults.json");
const PLAY_SOUND_SH = join(DIST, "hooks", "play-sound.sh");
const USER_CONFIG = join(homedir(), ".config", "zelda-sounds.json");

function readMoments(file: string): Record<string, string | null> {
  try {
    const data = JSON.parse(readFileSync(file, "utf8"));
    return (data.moments ?? {}) as Record<string, string | null>;
  } catch {
    return {};
  }
}

// Resolve the moment's sound (user override, else packaged default) and play it
// via the cross-platform shell player, detached so playback never blocks the bus.
function play(moment: string): void {
  const defaults = readMoments(DEFAULTS_JSON);
  const user = readMoments(USER_CONFIG);
  const sound = Object.prototype.hasOwnProperty.call(user, moment)
    ? user[moment]
    : defaults[moment];
  if (!sound) return;
  const soundPath = join(SOUNDS_DIR, sound);
  if (!existsSync(soundPath) || !existsSync(PLAY_SOUND_SH)) return;
  const child = spawn(PLAY_SOUND_SH, [soundPath], {
    stdio: "ignore",
    detached: true,
  });
  child.unref();
}

export const ZeldaSounds: Plugin = async ({ client }) => {
  // A child (subagent) session has `parentID` set; the root session does not.
  // session.idle carries only sessionID, so we fetch the Session to read it.
  async function isChildSession(sessionID: string): Promise<boolean> {
    try {
      const res = await client.session.get({ path: { id: sessionID } });
      return Boolean(res.data?.parentID);
    } catch {
      // If the session can't be resolved, treat it as a root session so the
      // task-complete cue still fires rather than being silently dropped.
      return false;
    }
  }

  return {
    event: async ({ event }) => {
      const eventType: string = event.type;
      if (eventType === "session.created") {
        play("session-started");
        return;
      }
      if (event.type === "session.idle") {
        const isChild = await isChildSession(event.properties.sessionID);
        play(isChild ? "subagent-done" : "task-complete");
        return;
      }
      if (eventType === "question.asked") {
        play("attention-needed");
        return;
      }
      if (eventType === "session.error") {
        play("error");
        return;
      }
      if (eventType === "tui.toast.show") {
        play("notification");
        return;
      }
      // Unmapped, dropped, and prompt-delivered moments invoke nothing.
    },
  };
};

export default ZeldaSounds;
