// GENERATED by build.mjs from plugins/zelda-sounds/bindings/opencode.json — DO NOT EDIT.
// Edit the canonical source under plugins/zelda-sounds/ and re-run `node build.mjs`.
//
// OpenCode plugin: plays Zelda sound cues on lifecycle events. Each bound event
// resolves the user's configured sound (from ~/.config/zelda-sounds.json or the
// packaged default) and spawns hooks/play-sound.sh directly — no Node/Bun
// runtime dependency required.

import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { homedir } from "node:os";
import type { Plugin } from "@opencode-ai/plugin";

// Resolve assets relative to this plugin file (<dist>/plugin/zelda-sounds.ts), so
// the distribution root is its parent's parent. We must NOT shell out to a JS
// runtime to run the .mjs player: OpenCode runs on a compiled Bun binary, so
// process.execPath is the opencode executable (not node) and would fail. Instead
// the plugin resolves the moment's sound itself and spawns the OS-native shell
// player (hooks/play-sound.sh) directly -- no node/bun dependency.
const DIST = dirname(dirname(fileURLToPath(import.meta.url)));
const SOUNDS_DIR = join(DIST, "sounds");
const DEFAULTS_JSON = join(DIST, "config", "defaults.json");
const PLAY_SOUND_SH = join(DIST, "hooks", "play-sound.sh");
const USER_CONFIG = join(homedir(), ".config", "zelda-sounds.json");

function readMoments(file: string): Record<string, string | null> {
  try {
    const data = JSON.parse(readFileSync(file, "utf8"));
    return (data.moments ?? {}) as Record<string, string | null>;
  } catch {
    return {};
  }
}

// Resolve the moment's sound (user override, else packaged default) and play it
// via the cross-platform shell player, detached so playback never blocks the bus.
// User config is read from the opencode section first (data.opencode.moments),
// with a legacy flat fallback (data.moments); defaults are always flat.
function play(moment: string): void {
  const defaults = readMoments(DEFAULTS_JSON);
  let userSound: string | null | undefined;
  try {
    const data = JSON.parse(readFileSync(USER_CONFIG, "utf8")) as any;
    userSound = data?.opencode?.moments?.[moment] ?? data?.moments?.[moment];
  } catch {
    // no user config — fall through to defaults
  }
  const sound = userSound !== undefined ? userSound : defaults[moment];
  if (!sound) return;
  const soundPath = join(SOUNDS_DIR, sound);
  if (!existsSync(soundPath) || !existsSync(PLAY_SOUND_SH)) return;
  const child = spawn(PLAY_SOUND_SH, [soundPath], {
    stdio: "ignore",
    detached: true,
  });
  child.unref();
}

export const ZeldaSounds: Plugin = async ({ client }) => {
  // A child (subagent) session has `parentID` set; the root session does
  // not. session.idle carries only sessionID, so we fetch the Session.
  async function isChildSession(sessionID: string): Promise<boolean> {
    try {
      const res = await client.session.get({ path: { id: sessionID } });
      return Boolean(res.data?.parentID);
    } catch {
      // If the session can't be resolved, treat it as a root session so
      // the task-complete cue still fires rather than being dropped.
      return false;
    }
  }

  // OpenCode plan mode == the read-only `plan` agent. At idle (the agent
  // stopped) read which agent ran the just-finished turn from its last
  // assistant message (`agent`/`mode`), so plan-ready fires only when the
  // plan agent stops. Never console.log/error here — it corrupts the TUI.
  async function lastTurnAgent(
    sessionID: string,
  ): Promise<string | undefined> {
    try {
      const res = await client.session.messages({ path: { id: sessionID } });
      const items: any[] = (res as any).data ?? [];
      for (let i = items.length - 1; i >= 0; i--) {
        const info = items[i]?.info;
        if (info?.role === "assistant") return info.agent ?? info.mode;
      }
    } catch {
      // If messages can't be read, fall through to the default cue.
    }
    return undefined;
  }

  // Track sessions whose most recent question was rejected (dismissed), so
  // the session.idle that immediately follows is suppressed rather than
  // mistaken for completion.
  const rejectedSessions = new Set<string>();

  return {
    event: async ({ event }) => {
      const eventType: string = event.type;
      if (eventType === "question.rejected") {
        const sid = (event as any).properties?.sessionID;
        if (sid) rejectedSessions.add(sid);
        return;
      }
      if (eventType === "session.created") {
        play("session-started");
        return;
      }
      if (event.type === "session.idle") {
        const sessionID = event.properties.sessionID;
        if (rejectedSessions.has(sessionID)) {
          rejectedSessions.delete(sessionID);
          return;
        }
        if (await isChildSession(sessionID)) {
          play("subagent-done");
          return;
        }
        const lastAgent = await lastTurnAgent(sessionID);
        if (lastAgent === "plan") {
          play("plan-ready");
          return;
        }
        play("task-complete");
        return;
      }
      if (eventType === "question.asked") {
        play("attention-needed");
        return;
      }
      if (eventType === "session.error") {
        play("error");
        return;
      }
      if (eventType === "tui.toast.show") {
        play("notification");
        return;
      }
      // Unmapped, dropped, and prompt-delivered moments invoke nothing.
    },
  };
};

export default ZeldaSounds;
